theme: jekyll-theme-Minimal
title: STAR Teknoloji StarTeknolojiSpace 
description: Star Teknoloji Hİzmetinizde Hoşgeldiniz. Google Haritalar ve Github Sayfalarında Bulabilirsiniz. Bİze Ayırdığınız Vakit için Teşekkür ederiz.NetCI NetStar Uygulamımızı Yakında GitHub MarketPlace Yayında Olacak.NetCI NetStar Uygulamımızı Yakında GitHub MarketPlace Yayında Olacak.NetCI NetStar Uygulamımızı Yakında GitHub MarketPlace Yayında Olacak.
twitter_username: guler_ercetin
email: ercetinguler@starteknoloji.space
yazar:  Erçetin Güler
remote_teheme: benbalter/retlab
